//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "departement")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id_dep: i32,
    pub nom_dep: String,
    pub id_dir: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::employe::Entity")]
    Employe,
}

impl Related<super::employe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Employe.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
